version: "3"

services:

  # PosgreSQL server
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    env_file:
      - postgres.env
    volumes:
      - data:/var/lib/postgresql/data

  # Starwars API app
  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
    env_file:
      - .env
    command: >
      sh -c "npm run typeorm:run-migrations &&
             npm run seeder:seed &&
             npm run start:dev"

volumes:
  data: