version: "3"

services:
  # PosgreSQL server
  db:
    image: postgres:13
    env_file:
      - postgres.env
    volumes:
      - data:/var/lib/postgresql/data

  # Starwars API app
  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
      - migration
      - seed
    env_file:
      - .env
    command: ["npm", "run", "start:prod"]

  # Migration service
  migration:
    build:
      context: .
    links:
      - db
    depends_on:
      - db
    command: ["npm", "run", "typeorm:run-migrations"]
    env_file:
      - .env
  
  # Seed service
  seed:
    build:
      context: .
    links:
      - db
    depends_on:
      - db
      - migration
    command: ["npm", "run", "seeder:seed"]
    env_file:
      - .env

volumes:
  data: